//code
int a =0 ;  
int b =1 ;  
int c =2 ;  
int d =3 ;  
int e =4 ;  
int f =5 ;  
int g =6 ;  
//code
int a1 =7 ;  
int b1 =8 ;  
int c1 =9 ;  
int d1 =10 ;  
int e1 =11 ;  
int f1 =12 ;  
int g1 =13 ;  
void setup(){
  for (int i = 0; i<13 ; i++){
    pinMode (i , OUTPUT);

}
}

void loop(){
  delay (1000);
  digitalWrite (a , HIGH);
  digitalWrite (b , HIGH);
  digitalWrite (c , HIGH);
  digitalWrite (d , HIGH);
  digitalWrite (e , HIGH);
  digitalWrite (f , HIGH);
  digitalWrite (g , LOW );
  delay (1000);
  digitalWrite (a , LOW);
  digitalWrite (b , HIGH);
  digitalWrite (c , HIGH);
  digitalWrite (d , LOW);
  digitalWrite (e , LOW);
  digitalWrite (f , LOW);
  digitalWrite (g , LOW );
  delay (1000);
  digitalWrite (a , HIGH);
  digitalWrite (b , HIGH);
  digitalWrite (c , LOW);
  digitalWrite (d , HIGH);
  digitalWrite (e , HIGH);
  digitalWrite (f , LOW);
  digitalWrite (g , HIGH );
  delay (1000);
  digitalWrite (a , HIGH);
  digitalWrite (b , HIGH);
  digitalWrite (c , HIGH);
  digitalWrite (d , HIGH);
  digitalWrite (e , LOW);
  digitalWrite (f , LOW);
  digitalWrite (g , HIGH );
  delay (1000);
  digitalWrite (a , LOW);
  digitalWrite (b , HIGH);
  digitalWrite (c , HIGH);
  digitalWrite (d , LOW);
  digitalWrite (e , LOW);
  digitalWrite (f , HIGH);
  digitalWrite (g , HIGH );
  delay (1000);
  digitalWrite (a , HIGH);
  digitalWrite (b , LOW);
  digitalWrite (c , HIGH);
  digitalWrite (d , HIGH);
  digitalWrite (e , LOW);
  digitalWrite (f , HIGH);
  digitalWrite (g , HIGH );
  delay (1000);
  digitalWrite (a , HIGH);
  digitalWrite (b , LOW);
  digitalWrite (c , HIGH);
  digitalWrite (d , HIGH);
  digitalWrite (e , HIGH);
  digitalWrite (f , HIGH);
  digitalWrite (g , HIGH );
  delay (1000);
  digitalWrite (a , HIGH);
  digitalWrite (b , HIGH);
  digitalWrite (c , HIGH);
  digitalWrite (d , LOW);
  digitalWrite (e , LOW);
  digitalWrite (f , LOW);
  digitalWrite (g , LOW );
  delay (1000);
  digitalWrite (a , HIGH);
  digitalWrite (b , HIGH);
  digitalWrite (c , HIGH);
  digitalWrite (d , HIGH);
  digitalWrite (e , HIGH);
  digitalWrite (f , HIGH);
  digitalWrite (g , HIGH );
  delay (1000);
  digitalWrite (a , HIGH);
  digitalWrite (b , HIGH);
  digitalWrite (c , HIGH);
  digitalWrite (d , HIGH);
  digitalWrite (e , LOW);
  digitalWrite (f , HIGH);
  digitalWrite (g , HIGH );
  delay (1000);
  
}



void loop(){
  delay (1000);
  digitalWrite (a1 , HIGH);
  digitalWrite (b1 , HIGH);
  digitalWrite (c1 , HIGH);
  digitalWrite (d1 , HIGH);
  digitalWrite (e1 , HIGH);
  digitalWrite (f1 , HIGH);
  digitalWrite (g1 , LOW );
  delay (1000);
  digitalWrite (a1 , LOW);
  digitalWrite (b1 , HIGH);
  digitalWrite (c1, HIGH);
  digitalWrite (d1 , LOW);
  digitalWrite (e1 , LOW);
  digitalWrite (f1, LOW);
  digitalWrite (g1 , LOW );
  delay (1000);
  digitalWrite (a1, HIGH);
  digitalWrite (b1 , HIGH);
  digitalWrite (c1 , LOW);
  digitalWrite (d1 , HIGH);
  digitalWrite (e1 , HIGH);
  digitalWrite (f1 , LOW);
  digitalWrite (g1 , HIGH );
  delay (1000);
  digitalWrite (a 1, HIGH);
  digitalWrite (b1 , HIGH);
  digitalWrite (c1 , HIGH);
  digitalWrite (d1 , HIGH);
  digitalWrite (e1 , LOW);
  digitalWrite (f1 , LOW);
  digitalWrite (g1 , HIGH );
  delay (1000);
  digitalWrite (a1 , LOW);
  digitalWrite (b1 , HIGH);
  digitalWrite (c1 , HIGH);
  digitalWrite (d1 , LOW);
  digitalWrite (e1 , LOW);
  digitalWrite (f1 , HIGH);
  digitalWrite (g1 , HIGH );
  delay (1000);
  digitalWrite (a1 , HIGH);
  digitalWrite (b1 , LOW);
  digitalWrite (c1 , HIGH);
  digitalWrite (d1 , HIGH);
  digitalWrite (e1 , LOW);
  digitalWrite (f1 , HIGH);
  digitalWrite (g1 , HIGH );
  delay (1000);
  digitalWrite (a1 , HIGH);
  digitalWrite (b1 , LOW);
  digitalWrite (c1 , HIGH);
  digitalWrite (d1 , HIGH);
  digitalWrite (e1 , HIGH);
  digitalWrite (f1 , HIGH);
  digitalWrite (g1 , HIGH );
  delay (1000);
  digitalWrite (a1 , HIGH);
  digitalWrite (b1 , HIGH);
  digitalWrite (c1 , HIGH);
  digitalWrite (d1 , LOW);
  digitalWrite (e1 , LOW);
  digitalWrite (f1 , LOW);
  digitalWrite (g1 , LOW );
  delay (1000);
  digitalWrite (a1 , HIGH);
  digitalWrite (b1 , HIGH);
  digitalWrite (c1 , HIGH);
  digitalWrite (d1 , HIGH);
  digitalWrite (e1 , HIGH);
  digitalWrite (f1 , HIGH);
  digitalWrite (g1 , HIGH );
  delay (1000);
  digitalWrite (a1 , HIGH);
  digitalWrite (b1 , HIGH);
  digitalWrite (c1 , HIGH);
  digitalWrite (d1 , HIGH);
  digitalWrite (e1 , LOW);
  digitalWrite (f1 , HIGH);
  digitalWrite (g1 , HIGH );
  delay (1000);
  
}